import type { Metadata } from 'next'
import { ReactNode } from 'react'
import { Header } from '@/components/shared/header'

export const metadata: Metadata = {
  title: 'Next Pizza | Главная',
  description: 'Generated by create next app'
}

export default function HomeLayout({
  children,
  modal
}: Readonly<{
  children: ReactNode
  modal: ReactNode
}>) {
  return (
    <main className='min-h-screen'>
      <Header />
      {children}
      {modal}
    </main>
  )
}
