import type { Metadata } from 'next'
import { ReactNode } from 'react'

export const metadata: Metadata = {
  title: 'Next Pizza | Главная',
  description: 'Generated by create next app'
}

export default function DashboardLayout({
  children
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <main className='min-h-screen'>
      <div>dfdsfdsfsd</div>
      {children}
    </main>
  )
}
